const currentUser = 'Arlinka';

i = 1;
const newId = () => `${i++}`;

const messagesData = [
  {
    text: "Good morning everyone!",
    createdAt: new Date("2020-10-06T20:01:00"),
    author: "Arlinka",
    isPersonal: false,
  },
  {
    text: "We've moved to Telegram. Come and join us there!",
    createdAt: new Date("2020-02-10T13:02:00"),
    author: "Arlinka",
    isPersonal: false,
  },
  {
    text: "Anyone to help there?",
    createdAt: new Date("2022-11-25T20:13:00"),
    author: "kvg-mur",
    isPersonal: false,
  },
  {
    text: "It's not working.",
    createdAt: new Date("2006-10-12T13:26:00"),
    author: "ORDANAX",
    isPersonal: true,
    to: "Arlinka",
  },
  {
    text: "I agree.",
    createdAt: new Date("2017-02-02T11:30:00"),
    author: "Arlinka",
    isPersonal: true,
    to: "ORDANAX",
  },
  {
    text: "Thanks, hope it's a nice day everywhere.",
    createdAt: new Date("2012-08-30T04:19:00"),
    author: "Irvalgilana",
    isPersonal: false,
  },
  {
    text: "I have to remember now.",
    createdAt: new Date("2018-07-12T12:17:00"),
    author: "kvg-mur",
    isPersonal: false,
  },
  {
    text: "Yeah, that's why he didn't want to continue there.",
    createdAt: new Date("2020-06-01T11:11:00"),
    author: "ORDANAX",
    isPersonal: false,
  },
  {
    text:
      "I think you should change it back to the other device and then check only on the volume preference.",
    createdAt: new Date("2001-07-27T20:27:00"),
    author: "mvaleryi",
    isPersonal: true,
    to: "kvg-mur",
  },
  {
    text: "There's almost no noise and your voice sound very clear.",
    createdAt: new Date("2000-07-27T04:15:00"),
    author: "kvg-mur ",
    isPersonal: true,
    to: "mvaleryi",
  },
  {
    text:
      "I can usually make out what they say, but I might or might not be able to make sense of the rhyming slang.",
    createdAt: new Date("2019-04-06T02:02:00"),
    author: "mvaleryi",
    isPersonal: true,
    to: "kvg-mur",
  },
  {
    text: "I can only use it with him though.",
    createdAt: new Date("2018-11-18T18:18:00"),
    author: "Chris Blade",
    isPersonal: false,
  },
  {
    text: "I also like to know some words in other languages.",
    createdAt: new Date("2019-02-10T11:00:00"),
    author: "ORDANAX",
    isPersonal: false,
  },
  {
    text: "So, if you practice you remember them if not will forget.",
    createdAt: new Date("2020-01-02T03:32:00"),
    author: "alexbabashov",
    isPersonal: false,
  },
  {
    text: "Not too bad. I'm working on my German right now. What about you?",
    createdAt: new Date("2012-01-04T17:17:00"),
    author: "Arlinka",
    isPersonal: false,
  },
  {
    text: "Hope you're doing great.",
    createdAt: new Date("2006-08-19T07:29:00"),
    author: "Irvalgilana ",
    isPersonal: true,
    to: "Arlinka",
  },
  {
    text:
      "Yes, they have a very extensive selection of languages, and some other courses as well.",
    createdAt: new Date("2007-11-25T13:52:00"),
    author: "Allhazeread",
    isPersonal: false,
  },
  {
    text: "So you have decided the path of the polyglot, that's great.",
    createdAt: new Date("2020-08-29T10:45:00"),
    author: "kvg-mur",
    isPersonal: false,
  },
  {
    text: "Have a nice chat guys.",
    createdAt: new Date("2009-05-24T11:11:00"),
    author: "ORDANAX",
    isPersonal: false,
  },
  {
    text: "And you!",
    createdAt: new Date("2018-12-04T21:49:00"),
    author: "Arlinka",
    isPersonal: true,
    to: "ORDANAX",
  },
];

const usersAll = [
    "Arlinka",
    "kvg-mur",
    "Allhazeread",
    "ORDANAX",
    "mvaleryi",
    "Chris Blade",
    "alexbabashov",
    "Irvalgilana",
    "eKlikkkkkkkkkeKlikkkk",
    "Ірина Денисюк",
    "Svengali",
    "WhiteApfel",
    "MATPAC",
    "shelpiAll",
    "hazereadForest",
    "RGSurge",
    "Blavatsimonov-89DJ",
    "NIKOLAY-D",
    "shaltay-boltay",
    "APOKALIPTIUS",
    "mvaleryideni_didroiganna",
    "TIMOHA69Evil",
    "Grimoire",
    "grunjaassasin",
    "filandrew_houplutik",
    "inkadykchanskiyAntonio",
    "grunjaassasin",
    "filandrew_houplutik",
    "inkadykchanskiyAntonio",
    "inkadykchanskiyAntonio",
    "grunjaassasin",
    "filandrew_houplutik",
    "inkadykchanskiyAntonio",
    "grunjaassasin",
  ];

const usersOnline = [
    "Arlinka",
    "kvg-mur",
    "Allhazeread",
    "ORDANAX",
    "mvaleryi",
    "Chris Blade",
    "alexbabashov",
    "Irvalgilana",
    "Grimoire",
    "grunjaassasin",
    "filandrew_houplutik",
    "inkadykchanskiyAntonio",
    "grunjaassasin",
    "filandrew_houplutik",
    "inkadykchanskiyAntonio",
    "inkadykchanskiyAntonio",
    "grunjaassasin",
    "filandrew_houplutik",
    "inkadykchanskiyAntonio",
    "grunjaassasin",
    "Blavatsimonov-89DJ",
    "NIKOLAY-D",
    "shaltay-boltay",
    "APOKALIPTIUS"
  ];